### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by ravener** [DasWolke/CloudStorm#12]
Hello,
 Is this still alive? Can't get it through npm, tried with git getting lot of node gyp errors about zlib sync

**Comment by DasWolke** [comment]
Hi there, it's still alive. Just not published on npm yet. :)

**Comment by ravener** [comment]
Oh okay didn't notice, btw do u know what's wrong with installation? Think it needs python as asked somewhere wanna make sure

**Comment by DasWolke** [comment]
You need to have build tools installed, aka a working node-gyp setup. Can be accomplished via `apt-get install build-essential` on the common linux installations, for further infos related to node-gyp you should probably consult the nodejs docs.
