### ISSUE TITLE
Memory leak in CloudStorm

### ISSUE THREAD

**Issue by anli5005** [DasWolke/CloudStorm#13]
There appears to be a memory leak somewhere in CloudStorm, possibly related to the `erlpack.node` library.

## Expected Behavior
CloudStorm uses a reasonable amount of memory upon startup (~1-2 MiB). This memory usage remains constant and does not increase over time, even as events in the server occur.

## Actual Behavior
CloudStorm starts out using 1 MiB of memory. After about 1-2 minutes, memory usage begins to increase. At 17 minutes of runtime, memory usage has risen to 27.03 MiB.

## RAM Profiling
Profiling to find this memory leak was done in [Instruments](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/index.html) using a boilerplate script (seen below).

Here are some of the screenshots illustrating CloudStorm's memory usage:
<img width="1284" alt="screen shot 2018-02-24 at 8 52 34pm" src="https://user-images.githubusercontent.com/7005789/36637198-cbc4c8ea-19a4-11e8-8d90-265cb91ad07e.png">

One screenshot appears to link the issue to `erlpack.node`:
<img width="1279" alt="screen shot 2018-02-24 at 8 54 38pm" src="https://user-images.githubusercontent.com/7005789/36637208-f5dbd998-19a4-11e8-8e0d-c3a9dfccfd4a.png">

Here's the full `.trace` file, if you'd like. It can be viewed in Instruments and should reveal more details.
[CloudStorm Allocations.trace.zip](https://github.com/DasWolke/CloudStorm/files/1755575/CloudStorm.Allocations.trace.zip)

## Code
The code I used to test and isolate this memory leak was fairly straightforward. Here it is:
```javascript
const CloudStorm = require('Cloudstorm');
let bot = new CloudStorm(process.env.BOT_TOKEN, {
    initialPresence: { status: 'online', game: { name: 'memory leaks. Fun!' } },
    firstShardId: 0,
    lastShardId: 0,
    shardAmount: 1
});

function ready() {
    console.log("CloudStorm ready");
}

function event(event) {
    console.log("=== RECEIVED AN EVENT ===");
    console.log(event.t);
}

bot.on("ready", ready);
bot.on("event", event);
bot.connect();
```

**Comment by anli5005** [comment]
If it helps, this issue only appears when `erlpack` is present in the `node_modules` folder.

**Comment by AnotherGenZ** [comment]
The above was tested on:
-MacOS
-Node v9.3
-x86 architecture

Will edit this as I find more information.
