### ISSUE TITLE
Client#disconnect not working as expected

### ISSUE THREAD

**Issue by MARCROCK22** [DasWolke/CloudStorm#17]
![imagen](https://user-images.githubusercontent.com/57925328/161352797-a91e5423-9e41-48be-b909-6d1ad0ff3bb2.png)

The websocket connection still alive after trying to disconnect it.

**Comment by PapiOphidian** [comment]
Client.connect doesn't resolve when all shards are ready. It resolves when the endpoint for bots has been fetched from SnowTransfer and then tells the shard manager to spawn the shards. That's it. You'd have to wait for each shard ready before disconnecting

**Comment by MARCROCK22** [comment]
> Client.connect doesn't resolve when all shards are ready. It resolves when the endpoint for bots has been fetched from SnowTransfer and then tells the shard manager to spawn the shards. That's it. You'd have to wait for each shard ready before disconnecting

![imagen](https://user-images.githubusercontent.com/57925328/161389259-df67b4c6-d2ce-4804-9879-0b2c0a4524f4.png)
![imagen](https://user-images.githubusercontent.com/57925328/161389264-28ef720c-b1dc-4d36-8cfa-76e7671e112d.png)

**Comment by PapiOphidian** [comment]
alright. I'll take a look at what's going on there since *that* certainly isn't supposed to happen

**Comment by PapiOphidian** [comment]
Fixed in 0.4.3
