### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by CleverSource** [DasWolke/CloudStorm#6]
So if this actual ever gets finished would you ever think about making a full modular bot out of your system rather than using something like discord.js, it would be cool to see this made with a real bot as well just some ideas for the bot if you did do this, moderation commands, music, fun, etc, and very beautiful rich embed help, you could even name the bot CloudStorm and the bot would run off CloudStorm! 👍

**Comment by DasWolke** [comment]
Hi There, no worries, im already building a bot with it 😄 , you gotta remember that cloudstorm is not the only component though, as there are other components for cache and rest too. Apart from that you should check out the dev branch, it covers the discord gateway completely and is pretty much done-ish
