### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CleverSource** [DasWolke/CloudStorm#7]
There is probally an easier way to ask questions but I just threw it in issues but is CloudStorm it's own thing or do RainCache and etc get used with CloudStorm also if I understood your reply to my old thing i'm looking forward to seeing an open source bot used with CloudStorm! :)

**Comment by Ahriana** [comment]
`CloudStorm / RainCache / StarGear / SnowTransfer` (more to come) are all micro services that can be tied together to make a functioning bot and would be used in tandem, they are **not** bots. That would be done yourself.

just a pre-warning this is all very much in development and not done.

**Comment by CleverSource** [comment]
Mhm, i'd love to see a working bot with all of them combined would be cool.

**Comment by Ahriana** [comment]
they are our there, however are not in a production state, this is all very early in development and has alot of work remaining

**Comment by DasWolke** [comment]
Closing this since not a real issue 👀
